~/software/gromos---1.5.0/programs/dGslv_pbsolv @f dGslv_pbsolv_L_0.0.arg > dGslv_pbsolv_L_0.0.out
~/software/gromos---1.5.0/programs/dGslv_pbsolv @f dGslv_pbsolv_L_0.05.arg > dGslv_pbsolv_L_0.05.out
~/software/gromos---1.5.0/programs/dGslv_pbsolv @f dGslv_pbsolv_L_0.1.arg > dGslv_pbsolv_L_0.1.out
~/software/gromos---1.5.0/programs/dGslv_pbsolv @f dGslv_pbsolv_L_0.2.arg > dGslv_pbsolv_L_0.2.out
~/software/gromos---1.5.0/programs/dGslv_pbsolv @f dGslv_pbsolv_L_0.3.arg > dGslv_pbsolv_L_0.3.out
~/software/gromos---1.5.0/programs/dGslv_pbsolv @f dGslv_pbsolv_L_0.4.arg > dGslv_pbsolv_L_0.4.out
~/software/gromos---1.5.0/programs/dGslv_pbsolv @f dGslv_pbsolv_L_0.5.arg > dGslv_pbsolv_L_0.5.out
~/software/gromos---1.5.0/programs/dGslv_pbsolv @f dGslv_pbsolv_L_0.6.arg > dGslv_pbsolv_L_0.6.out
~/software/gromos---1.5.0/programs/dGslv_pbsolv @f dGslv_pbsolv_L_0.7.arg > dGslv_pbsolv_L_0.7.out
~/software/gromos---1.5.0/programs/dGslv_pbsolv @f dGslv_pbsolv_L_0.8.arg > dGslv_pbsolv_L_0.8.out
~/software/gromos---1.5.0/programs/dGslv_pbsolv @f dGslv_pbsolv_L_0.9.arg > dGslv_pbsolv_L_0.9.out
~/software/gromos---1.5.0/programs/dGslv_pbsolv @f dGslv_pbsolv_L_1.0.arg > dGslv_pbsolv_L_1.0.out
